name: Criptografando-arquivos

on:
  push:
    branches:
      - main

jobs:
  installing-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python packet
        uses: actions/setup-python@v2 

      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip 
          python -m pip install --upgrade setuptools
          wget https://files.pythonhosted.org/packages/74/bb/9003d081345e9f0451884146e9ea2cff6e4cc4deac9ffd4a9ee98b318a49/hashlib-20081119.zip
          unzip hashlib-20081119.zip
          pip install hashlib
          
